### PR TITLE
Gets Wake Establishment Types

### PR DESCRIPTION
**Pull request by JonathanFrederick**
Adds establishment types to import_wake
Adds my username and public key to devs.sls

@victor-rocha Once I get server access, I can run a script that updates Establishments to have the correct type

### CODE REVIEW

**Comment by victor-rocha** [comment]
This looks good but let's make one more changes so that the map continues to work:
https://github.com/codefordurham/food-inspector/blob/develop/inspections/views.py#L21

**Comment by JonathanFrederick** [comment]
Do you want to remove the type filter?  The map is working for me locally after getting types into the Wake data.

**Comment by victor-rocha** [comment]
Yes, but we are only displaying establishment of type 1. Unless that's what we really want.

**Comment by JonathanFrederick** [comment]
My only hesitation to showing all types would have been clutter, but these seem to be the numbers:
Food Stand: 583
Limited Food Service: 22
Meat Market: 95
Restaurant: 2118
Public School Lunchrooms: 165
Mobile Food Units: 74
Institutional Food Service: 46
Private School Lunchrooms: 15
Pushcarts: 43
Elderly Nutrition Sites (catered): 8

**Comment by JonathanFrederick** [comment]
Colin made the change?
https://github.com/codefordurham/food-inspector/commit/3beb168d1a5ccd26dab688db3a935caefd7ca029

**Comment by victor-rocha** [comment]
It was an offline discussion. I am okay either way. :+1:

**Comment by JonathanFrederick** [comment]
I think I'm inclined to leave it for now and discuss it more later, though personally I would like to see more, if not all types.

**Pull request merged**
