### PR TITLE
Importing Wake Data

### PR DESCRIPTION
**Pull request by JonathanFrederick**
This provides the functionality to import most of the available wake county data.  There are still a couple unresolved issues with the data and if/how we want to handle those discrepancies.

### CODE REVIEW

**Comment by victor-rocha** [comment]
Looks good, do you want to handle setting up a celery task in this PR or do you want to work on that separately?

**Comment by JonathanFrederick** [comment]
I'll try to get it in here, though I haven't worked with Celery before.

**Comment by victor-rocha** [comment]
A lot of the configuration is already there, I think, so just focus on creating a task and then look into the task scheduler. http://docs.celeryproject.org/en/latest/django/first-steps-with-django.html

**Comment by JonathanFrederick** [comment]
I have a task I believe should work, but I'm still struggling with running a Celery worker to test it

**Comment by JonathanFrederick** [comment]
@victor-rocha Could you let me know what I'm supposed to have in my .env for this on Slack?

**Comment by victor-rocha** [comment]
@JonathanFrederick Hey, sorry. Long weekend. I have never really called a management command from a task like this. It should work in Theory. We would still need to add a setting in django settings that tells django/celery when to fireup the task. Alternatively, we could just add a cron job for now. Have all the data issue been address? Will that be something that affect us? Have you look at the frontend after all the data has been loaded to verify that all the restaurants show up?

**Comment by JonathanFrederick** [comment]
@victor-rocha I was able to run the contents of the task from the python terminal, so that much should work.  I've now mimicked the Durham entry in CELERYBEAT_SCHEDULE for importing Wake data, but I'm still not sure how to check that it's working.

**Comment by victor-rocha** [comment]
This looks good. Feel free to merge any time and I will deploy it to the server.

**Comment by JonathanFrederick** [comment]
What is your opinion on forking vs. working in this repo?

**Comment by victor-rocha** [comment]
I would prefer if we work off this repo but whatever makes sense to the project.

**Pull request merged**
